### ISSUE TITLE
Missing link in tutorial

### ISSUE THREAD

**Issue by eggsyntax** [fulcrologic/fulcro-getting-started#2]
I'm excited to finally be checking out Fulcro! I'm pretty impressed with what I've seen so far :)

I got to the interactive tutorial [from the book](http://book.fulcrologic.com/#_getting_started). The first tutorial says, 
`This file, for example, is in src/tutorial/fulcro_tutorial/A_Introduction.cljs. If you followed the README to start up this project...`

Unfortunately, it's not clear from that where the README lives or where you'd go to run the project locally. I suggest maybe linking "README" to the [getting-started repo](https://github.com/fulcrologic/fulcro-getting-started).

Thanks again, and in particular, thanks for creating such a terrific wealth of documentation! Miles above most of the projects in Clojure/Script-world (including my own ;) ).

**Comment by eggsyntax** [comment]
Relatedly, it's unclear how to run the tutorial locally unless you happen to be starting from the main site [README](https://github.com/fulcrologic/fulcro). I see now, from there, that I actually have to clone the *main* Fulcro repo and do `./run-tutorial` from there. That's not mentioned if you're starting at the hosted version of the interactive tutorial. So this is, I guess, the wrong repo to have filed this issue in -- I'll leave it open just so that you'll be aware of the issue, though.

**Comment by awkay** [comment]
Thanks. I'll see if I can get these fixed tomorrow. occupied today.

**Comment by eggsyntax** [comment]
No rush on my account, I'm all set. Just wanted to make you aware.

**Comment by awkay** [comment]
I've added a NOTE in the introduction. Hopefully that will help.
